"""GcodeValidator accepts real toolpath G-code, rejects empty/garbage, and extracts stats."""

from ncad.cam.gcode_validator import GcodeValidator

_GOOD = """; generated by test
G21 ; mm
G90 ; absolute
M104 S200
;LAYER:0
G1 X10 Y10 Z0.2 E1.5 F1200
;LAYER:1
G1 X20 Y20 Z0.4 E3.0
M104 S0
"""


def test_valid_gcode_passes_with_stats():
    result = GcodeValidator().validate(_GOOD)
    assert result["valid"] is True
    assert result["reasons"] == []
    stats = result["stats"]
    assert stats["motion_commands"] == 2
    assert stats["layers"] == 2
    assert stats["has_extrusion"] is True


def test_empty_is_invalid():
    result = GcodeValidator().validate("   \n  \n")
    assert result["valid"] is False
    assert any("empty" in r for r in result["reasons"])


def test_no_motion_commands_is_invalid():
    # Only comments + setup codes (G21/G90/M104), no G0/G1 moves.
    result = GcodeValidator().validate("; header\nG21\nG90\nM104 S200\n")
    assert result["valid"] is False
    assert any("motion" in r for r in result["reasons"])


def test_g10_and_g28_are_not_linear_moves():
    # G10 (retract) / G28 (home) must not be counted as G1 linear moves.
    result = GcodeValidator().validate("G28\nG10\n")
    assert result["stats"]["motion_commands"] == 0
    assert result["valid"] is False


def test_motion_without_axis_words_is_invalid():
    # A G1 with only a feedrate/extrude and no X/Y/Z is not a real toolpath move.
    result = GcodeValidator().validate("G1 F1200\nG1 E2.0\n")
    assert result["valid"] is False
    assert any("axis" in r for r in result["reasons"])


def test_non_extruding_gcode_is_still_valid():
    # A CNC/laser path (no E word) is valid G-code; has_extrusion just reports False.
    result = GcodeValidator().validate("G21\nG1 X5 Y5 F600\nG1 X10 Y10\n")
    assert result["valid"] is True
    assert result["stats"]["has_extrusion"] is False
